export default {
    FONT_SIZE_SMALL: 12,
    FONT_SIZE_LARGE: 22,
    PRIMARY_COLOR: '#95c42c',
    SECONDARY_COLOR: '#005014',
    BACKGROUND_COLOR: '#e4e4e4',
    BACKGROUND_COLOR_SECONDARY: '#FFFFFF',
    COLOR_BLACK: '#000000',
    FONT_WEIGHT_LIGHT: 200,
    FONT_WEIGHT_MEDIUM: 600,
    FONT_WEIGHT_HEAVY: 'bold'
  };