export enum MenuPathEnum {
  SETTINGS = 'Configuración',
  SETTINGS_HOME = 'Configuraciones',
  LOGOUT = 'Salir',
  LOGIN = 'Login',
  JORNADA = 'JORNADAS',
  JORNADA_HOME = 'Inicio',
  MOVIMIENTO_HOME = 'Movimientos',
  MOVIMIENTO_TAB = 'MovimientoTab',
  MOVIMIENTO = 'Movimiento',
  MOVIMIENTO_LIST = 'MovimientoList',
  TAREA_CREATE = 'CrearTarea',
  TAREA_EDIT = 'EditarTarea',
  TAREA_DETALLE = 'DetalleTarea',
  TAREA_ATTEND = 'Tarea',
  CLIENTE_HOME = 'Productos',
  PRODUCTO = 'Catalogo',
  CLIENTE_DETAIL = 'ClienteDetalle',
  CLIENTE_CREATE = 'ClienteCrear',
}